### ISSUE TITLE
"Feature" request

### ISSUE THREAD

**Issue by Jese44** [warrior25/HA-Nysse#7]
That Nysse alerts was cool addition, thanks for the update!
Whenever you have extra time, could you create an example for a card how to pull data out of the alert (attributes) and show it in clean format (alert #, description, effective from dd.mm.-dd.mm.yyyy) I've been trying to use markdown card and implementing the same method as we discussed back with the "Example HTML to include n amount in display" -issue but i have no enough knowledge to get it working.

...I'd show the alert data on a wall tablet but atm the presentation is uglyish:
![image](https://github.com/warrior25/HA-Nysse/assets/45014337/04b355e0-ce4f-43de-ae0d-e2f37c006fb1)

```
type: entity
entity: sensor.nysse_service_alerts
name: nysse alert
attribute: alerts
```

extra: Maybe add some sort of filtering on what alerts to show, i.e. pick the lines to follow (idk if this is possible):
alert 1: Event in nokia arena, buses re-routed
alert2: bus stop nnnn out of order (line yy stop) due to whatever reason.

**Comment by warrior25** [comment]
A frontend example for displaying service alerts will be available in the readme of v.1.2. As for filtering the alerts, there is no information about which stops or lines they relate to. Checking if the alert description contains the stop code could help with this.
```yaml
  {% set alerts = state_attr('sensor.nysse_service_alerts','alerts')
  %} {% for i in range(0, alerts | count, 1) %}

  {% if '0014' in alerts[i].description %}
    <b>{{ alerts[i].start.strftime('%d.%m.%Y') }} - {{ alerts[i].end.strftime('%d.%m.%Y') }}</b><br>
    {{ alerts[i].description }}<br><br>
  {% endif %}

  {% endfor %}
```
Replace 0014 with your preferred stop code.

**Comment by Jese44** [comment]
Thank you!
